spring.application.name=studentApp


spring.datasource.url = jdbc:postgresql://localhost:5400/studentManagement
spring.datasource.username = postgres
spring.datasource.password = INALA
spring.jpa.show.sql = true
spring.properties.hibernate.dialect = org.hibernate.dialect.PostgresPlusDialect
###create, drop, validate, update
spring.jpa.hibernate.ddl-auto = update